mode: "dev"

video_dir_path: "./public/video-export-grouped"

server:
  port: 6305

logger:
  level: "debug"
  filename: "./log/shafurui.log"
  max_size: 100 # 单文件最大体积，单位 MB
  max_age: 30 # 历史日志最大保留天数，单位 day
  max_backups: 5

database:
  mysql:
    addr: "localhost:3306"
    user: "root"
    password: "123456"
    db_name: "shafurui"

jwt:
  secret: "foobarorange"
  access_expires_in: "2h"
  refresh_expires_in: "72h"

auth:
  whitelist:
    - "GET:/foo"
    - "GET:/@vite/client"
    - "GET:/"
    - "POST:/app/getHelloInfo"
  default_user:
    userid: 1
    username: "foo"
    password: "foo123"
    nickname: "奔跑的椰子"
