@hostname = localhost
@port = 6305
@host = {{hostname}}:{{port}}
@token = replace-with-access-token
@refreshToken = replace-with-refresh-token

### AuthLogin
post http://{{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "foo1",
  "password": "foo123"
}

### AuthRefresh
post http://{{host}}/api/auth/refresh HTTP/1.1
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}
